desktop_width:
  default: 1440
  min: 320
  max: 3840

aspect_ratio_width:
  default: 16
  min: 1
  max: 64

aspect_ratio_height:
  default: 9
  min: 1
  max: 64

iframe_border:
  default: "1px solid var(--primary-low)"
  type: string
